/*
 * build-embed.js
 *
 * Bundles the vendored Mozilla Readability library together with the widget
 * source into a single, self-contained `public/embed.js`. No build tooling,
 * no bundler, no runtime CDN dependency — just file concatenation inside one
 * IIFE so `Readability` is in scope for the widget code.
 *
 * Run:  node build-embed.js
 */
const fs = require("fs");
const path = require("path");

const root = __dirname;
const readability = fs.readFileSync(
  path.join(root, "public", "vendor", "Readability.js"),
  "utf8"
);
const widget = fs.readFileSync(
  path.join(root, "public", "src", "widget.js"),
  "utf8"
);

const banner =
  "/*! Listen-to-this-article embed widget\n" +
  " *  Bundle = Mozilla Readability (Apache-2.0) + widget logic.\n" +
  " *  Generated by build-embed.js — do not edit by hand. Edit public/src/widget.js.\n" +
  " */\n";

const out =
  banner +
  "(function () {\n" +
  '"use strict";\n' +
  "// --- vendored Mozilla Readability ---\n" +
  readability +
  "\n// --- widget ---\n" +
  widget +
  "\n})();\n";

const outPath = path.join(root, "public", "embed.js");
fs.writeFileSync(outPath, out, "utf8");
console.log(
  "Wrote " + outPath + " (" + (out.length / 1024).toFixed(1) + " KB)"
);
